# Generated by Django 6.0.6 on 2026-07-05 22:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Где выполнять привычку?",
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Во сколько выполнять привычку?", verbose_name="Время"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Что конкретно нужно сделать?",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="True = приятная привычка (без вознаграждения), False = полезная привычка",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем себя порадовать после выполнения?",
                        max_length=255,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Каждый день"),
                            (2, "Раз в 2 дня"),
                            (3, "Раз в 3 дня"),
                            (4, "Раз в 4 дня"),
                            (5, "Раз в 5 дней"),
                            (6, "Раз в 6 дней"),
                            (7, "Раз в 7 дней"),
                        ],
                        default=1,
                        help_text="Как часто выполнять привычку (в днях)",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Сколько секунд займёт выполнение (макс. 120)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Время на выполнение (сек)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="True = видна всем пользователям",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "last_completed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее выполнение"
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка, которая будет вознаграждением за выполнение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_to",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
    ]
